### ISSUE TITLE
ckpt库中的bin文件

### ISSUE THREAD

**Issue by 19357514352** [kangbrilliant/DCA-Net#3]
请问bin文件是论文中最好结果的保存模型吗

**Comment by kangbrilliant** [comment]
bin文件不是论文中最好结果的保存模型，但使用该bin文件获得的指标，是大于等于论文里报告的指标。

原因是我们提交论文儿之后，又搜索了一些超参，指标虽然比论文中的要高一些，但我们认为好的方法不应以调参取胜，所以就没有在论文里更新指标
