### ISSUE TITLE
关于添加BERT代码复现问题

### ISSUE THREAD

**Issue by letsgocoder** [kangbrilliant/DCA-Net#8]
您好，请问您方便发我一份BERT+DCA NET的相关代码和相关系数吗？我想要复现一下您的结果 。

**Comment by zsc19** [comment]
我也有同样的需求！

**Comment by RolandYang** [comment]
我也有同样的需求！

**Comment by qinlibo-hit** [comment]
@letsgocoder @zsc19 @RolandYang 感谢大家对我们工作感兴趣，在BERT上的相关实验上，我们当时仔细精调了参数学习率1e-6到1e-5，以及batch-size，希望对大家调参有所帮助。有任何问题欢迎联系邮箱m15840540712@163.com
